apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
 containers:
 - image: techworldwithsiva/stress
   imagePullPolicy: Always
   name: stress
   command: ["sleep" , "200"]
   resources:
    requests:
      cpu: "150m"
      memory: "200Mi"  
    limits:
      cpu: "200m"  
      memory: "300Mi"
   