apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: docker
    - name: learning
      value: saroja
    - name: duration
      value: 25hrs     

